# Generated by Django 4.0.2 on 2022-02-26 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
